name: mutyper
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - bcftools
  - tabix
  - libcurl
  - bzip2
  - gcc
  - pip
  - pip:
    - -r requirements.txt
    - . # installs package from current directory
