name: mutyper_test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - bcftools
  - tabix
  - pip
  - pip:
    - -r requirements.txt
    - . # installs package from current directory
