name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9, '3.10', 3.11]  # https://github.com/actions/runner/issues/1989
        include:
          - os: ubuntu-latest
            compiler: gcc_linux-64
          - os: macos-latest
            compiler: clang_osx-64

    runs-on: ${{ matrix.os }}

    defaults:
      # must specify the shell so that conda init updates bashrc see: https://github.com/conda-incubator/setup-miniconda#IMPORTANT
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install miniconda and create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: mutyper
          channels: bioconda,conda-forge,defaults
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          auto-update-conda: true

      - name: Install
        run: |
          conda install bcftools tabix pip ${{ matrix.compiler }}
          make install

      - name: Lint
        run: make lint

      - name: Check format with black
        run: black --check mutyper

      - name: Test
        run: make test

      - name: Test docs build
        run: |
          make docs
